### ISSUE TITLE
Email adress cessda@training.eu

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#1]
Add SO (Lisa, Julia) to the email adresses cessda@training.eu is forwarded to

**Comment by hirschlisa** [comment]
Hi @alen-vodopijevec-cessda, have you gotten around to adressing this yet?

**Comment by hirschlisa** [comment]
Hi @alen-vodopijevec-cessda is there any movement on this?

**Comment by alen-vodopijevec-cessda** [comment]
Training@cessda.eu is now configured as an alias - forwarding all incoming emails to Lisa and Julia, and also to Alen@cessda just for testing purposes (will be removed soon)
