### ISSUE TITLE
CESSDA Zenodo community 

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#2]
Add SO to the CESSDA Zenodo community

** open question: **how many accounts can be linked to a community?

**Comment by hirschlisa** [comment]
Is there any movement on this issue yet? Other issues depend on access to Zenodo (i..e the DOI that does not resolve etc, see issue #6  )

**Comment by alen-vodopijevec-cessda** [comment]
Dear Lisa, can you let me know you account name on Zenodo?

**Comment by hirschlisa** [comment]
lisa.hirsch@univie.ac.at, username lisahirsch

**Comment by alen-vodopijevec-cessda** [comment]
Intivation for the "Manager" role sent.

**Comment by hirschlisa** [comment]
Invitation accepted
