### ISSUE TITLE
CESSDA YouTube Channel

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#3]
Give SO access to the YouTube Channel

** open question **
Who owns the channel, communications?

**Comment by alen-vodopijevec-cessda** [comment]
@hirschlisa Can you please send me Google accounts that should be added as moderators?

**Comment by hirschlisa** [comment]
hirsch.lisa.l.h@gmail.com

**Comment by hirschlisa** [comment]
Was the invitation already sent out? Currently I do not see the CESSDA account in my account. Please let me know if you need any more info.

**Comment by alen-vodopijevec-cessda** [comment]
@hirschlisa  Invitation sent, please check now.

**Comment by hirschlisa** [comment]
it worked!
