### ISSUE TITLE
CESSDA Zoom account

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#42]
Add SO to CESSDA Zoom account or give access after resetting passwords.

**Comment by hirschlisa** [comment]
Hi @alen-vodopijevec-cessda is there any movement on this?

**Comment by alen-vodopijevec-cessda** [comment]
@hirschlisa .. We have one other connected issue with the Zoom account that is in the process of resolving. If you need access in the meantime please let me know.

**Comment by hirschlisa** [comment]
Will let you know if I need access immediately, we have some webinars coming up in the next months for the Infra4NextGen where we will need access. How much in advance should I let you know (registration links etc need to go out with invites in advance)? 

It is also definitely vital for the general set up of the TR as I cannot plan any events atm if I do not know how to provide Zoom access, nor can I continue writing the documentation. Do you know when the issue will be resolved? That would allow me to plan a bit better and allow me to allocate my resources more effectively.

**Comment by alen-vodopijevec-cessda** [comment]
@hirschlisa  I've sent you connection details for the Zoom account.

Please check and feel free to update account details accordingly.
