### ISSUE TITLE
Metadata primary language

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#43]
List of primary languages is no free text field, but contains a drop down list with English, German, French only. Can that be adapted to better reflect the diversity of languages amongst CESSDA SPs?

**Comment by alen-vodopijevec-cessda** [comment]
@hirschlisa Can you provide a list of languages that you expect to be present in the dorpdown?

**Comment by openconcept** [comment]
By the Training working group's request, the list was restricted to keep it as small as possible. It is easy to add more languages following a request from CESSDA.

**Comment by hirschlisa** [comment]
If there is no technical reason for keeping the list short I would greatly appreciate adding all languages from CESSDA SPs to the list. Concretely, the ones that are missing right now are Hungarian, Macedonian, Slovene/Slovenian. 

The full list of languages (to be added to German, English French right now) following the list of SPs here (https://www.cessda.eu/About/Consortium-and-Partners/List-of-Service-Providers): Dutch, BCMS, Czech, Finnish, Greek, Hungarian, Icelandic, Italian, Macedonian, Norwegian, Portuguese, Slovak, Swedish

**Comment by alen-vodopijevec-cessda** [comment]
I played around a bit and asked ChatGPT for a list and it produced the following:
--
Here is the updated list with the additional countries:

1. **Austria** - German
2. **Belgium** - Dutch (Dutch, French, and German are official, but Dutch is the most widely spoken)
3. **Croatia** - Croatian
4. **Czech Republic** - Czech
5. **Finland** - Finnish (Finnish and Swedish are official, but Finnish is the most widely spoken)
6. **France** - French
7. **Germany** - German
8. **Greece** - Greek
9. **Hungary** - Hungarian
10. **Iceland** - Icelandic
11. **Ireland** - Irish (English and Irish are official, but Irish is the national and first official language)
12. **Italy** - Italian
13. **Netherlands** - Dutch
14. **North Macedonia** - Macedonian
15. **Norway** - Norwegian
16. **Slovenia** - Slovene
17. **Sweden** - Swedish
18. **Switzerland** - German (German, French, Italian, and Romansh are official, but German is the most widely spoken)
19. **United Kingdom (UK)** - English
20. **Portugal** - Portuguese
21. **Serbia** - Serbian
22. **Slovakia** - Slovak

So, the clean list without duplicates would be:
"German, Dutch, Croatian, Czech, Finnish, French, Greek, Hungarian, Icelandic, Irish, Italian, Macedonian, Norwegian, Slovene, Swedish, English, Portuguese, Serbian, Slovak"

**Comment by openconcept** [comment]
I've updated the list and arranged them alphabetically. The additional languages are now available for Training resources.

**Comment by hirschlisa** [comment]
thanks for the quick fix!
