### ISSUE TITLE
crd-3737 | DOI does not resolve

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#6]
For the resource crd-3737 the DOI (https://doi.org/10.5281/zenodo.10118731) does not resolve

**Comment by alen-vodopijevec-cessda** [comment]
This record is removed from Zenodo - that's why DOI is not resolving.

I found this version https://zenodo.org/records/10492184

Can you please check (update) that and see "Version" information. When citing Zenodo records, there is an "catch-all" URL for all versions of particular record resolving to the latest.

--
Alen

**Comment by hirschlisa** [comment]
The link you sent is the webinar recording though, not the slides themselves. For all other events in the past whoever uploaded the materials before me being SO did two seperate entries (in the TR and on Zenodo) for the recoding on one hand (that is the DOI that does resolve, training resource entry see https://www.cessda.eu/Training-Resources/Resource-crd-3758) and the slides on the other hand (that is the DOI that does not resolve, training resource entry see https://www.cessda.eu/Training-Resources/Resource-crd-3737). So in this instance, the DOI for the slides does not resolve.

**Comment by hirschlisa** [comment]
I held this webinar myself, and it was communicated to me that the slides would also end up on Zenodo. If it is no issue with the already reserved DOI I can also upload the slides myself now that the Zenodo access works for me, and simply update the corresponding DOI in the CESSDA Training Resources.

**Comment by alen-vodopijevec-cessda** [comment]
> I held this webinar myself, and it was communicated to me that the slides would also end up on Zenodo. If it is no issue with the already reserved DOI I can also upload the slides myself now that the Zenodo access works for me, and simply update the corresponding DOI in the CESSDA Training Resources.

That would be the right solution in my opinion.

**Comment by hirschlisa** [comment]
Irena ended up fixing it because I had asked her about this in June befoer I had any access to Zenodo. DOI resolves now.
